### PR TITLE
Bitmap bug fix

### PR DESCRIPTION
**Pull request by marjasi**

### CODE REVIEW

**Comment by marjasi** [comment]
[[Bug] Bitmap recycled](https://trello.com/c/Kh9Kc7b5/88-bug-bitmap-recycled)

**Comment by EdvardasDlugauskas** [comment]
Why does this have changes from #49 as well? Confusing

**Comment by marjasi** [comment]
> Why does this have changes from #49 as well? Confusing

Because I made this branch off of the exception-handling-permissions. I think I should have made a new branch from new-design-and-refactoring instead.

**Comment by marjasi** [comment]
I'll close this PR, delete this branch and create a new branch.

**Pull request closed without merging**
